const searchData = {
  search: {
    repositoryCount: 17822,
    pageInfo: {
      startCursor: "Y3Vyc29yOjE=",
      hasNextPage: true,
      endCursor: "Y3Vyc29yOjEy",
      __typename: "PageInfo",
    },
    repositories: [
      {
        id: "MDEwOlJlcG9zaXRvcnk0MDIzODk0MA==",
        name: "Localize-Swift",
        nameWithOwner: "marmelroy/Localize-Swift",
        description:
          "Swift friendly localization and i18n with in-app language switching",
        updatedAt: "2022-06-29T04:09:37Z",
        createdAt: "2015-08-05T10:19:09Z",
        pushedAt: "2021-10-24T15:24:51Z",
        stargazerCount: 2823,
        viewerHasStarred: false,
        url: "https://github.com/marmelroy/Localize-Swift",
        primaryLanguage: {
          color: "#F05138",
          name: "Swift",
          id: "MDg6TGFuZ3VhZ2UzNzE=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkzOTA2Njk=",
        name: "localized",
        nameWithOwner: "cakephp/localized",
        description: "I18n and L10n related CakePHP code",
        updatedAt: "2022-06-21T15:39:01Z",
        createdAt: "2009-11-30T20:19:49Z",
        pushedAt: "2022-04-23T20:15:40Z",
        stargazerCount: 214,
        viewerHasStarred: false,
        url: "https://github.com/cakephp/localized",
        primaryLanguage: {
          color: "#4F5D95",
          name: "PHP",
          id: "MDg6TGFuZ3VhZ2UxNTE=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnk5OTAyMjU4Mg==",
        name: "react-native-localize",
        nameWithOwner: "zoontek/react-native-localize",
        description: "🌍 A toolbox for your React Native app localization",
        updatedAt: "2022-07-02T17:11:06Z",
        createdAt: "2017-08-01T16:38:22Z",
        pushedAt: "2022-06-24T11:28:21Z",
        stargazerCount: 1797,
        viewerHasStarred: false,
        url: "https://github.com/zoontek/react-native-localize",
        primaryLanguage: {
          color: "#b07219",
          name: "Java",
          id: "MDg6TGFuZ3VhZ2UxNTg=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnk5ODY4OQ==",
        name: "jquery-localize",
        nameWithOwner: "coderifous/jquery-localize",
        description:
          "a jQuery plugin that makes it easy to internationalize your web site.  ",
        updatedAt: "2022-06-08T12:01:23Z",
        createdAt: "2008-12-30T23:21:38Z",
        pushedAt: "2017-07-09T16:49:49Z",
        stargazerCount: 471,
        viewerHasStarred: false,
        url: "https://github.com/coderifous/jquery-localize",
        primaryLanguage: {
          color: "#f1e05a",
          name: "JavaScript",
          id: "MDg6TGFuZ3VhZ2UxNDA=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkxMjM2NzIyNA==",
        name: "laravel-localization",
        nameWithOwner: "mcamara/laravel-localization",
        description: "Easy localization for Laravel",
        updatedAt: "2022-06-30T16:57:24Z",
        createdAt: "2013-08-25T23:14:30Z",
        pushedAt: "2022-06-21T14:04:37Z",
        stargazerCount: 2928,
        viewerHasStarred: false,
        url: "https://github.com/mcamara/laravel-localization",
        primaryLanguage: {
          color: "#4F5D95",
          name: "PHP",
          id: "MDg6TGFuZ3VhZ2UxNTE=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnk3NjEwMjY4Mw==",
        name: "Localize",
        nameWithOwner: "freshOS/Localize",
        description: "🏁 Automatically clean your Localizable.strings files",
        updatedAt: "2022-06-29T01:29:46Z",
        createdAt: "2016-12-10T09:19:38Z",
        pushedAt: "2020-05-15T06:30:29Z",
        stargazerCount: 333,
        viewerHasStarred: false,
        url: "https://github.com/freshOS/Localize",
        primaryLanguage: {
          color: "#F05138",
          name: "Swift",
          id: "MDg6TGFuZ3VhZ2UzNzE=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkxNTYzNjk1NDA=",
        name: "Office-Tool",
        nameWithOwner: "YerongAI/Office-Tool",
        description: "Office Tool Plus localization projects.",
        updatedAt: "2022-07-02T04:39:26Z",
        createdAt: "2018-11-06T10:54:58Z",
        pushedAt: "2022-07-02T14:45:13Z",
        stargazerCount: 4701,
        viewerHasStarred: false,
        url: "https://github.com/YerongAI/Office-Tool",
        primaryLanguage: null,
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkxMzg1ODkw",
        name: "pontoon",
        nameWithOwner: "mozilla/pontoon",
        description: "Mozilla's Localization Platform",
        updatedAt: "2022-07-02T10:54:00Z",
        createdAt: "2011-02-19T11:25:51Z",
        pushedAt: "2022-06-27T15:40:13Z",
        stargazerCount: 1166,
        viewerHasStarred: false,
        url: "https://github.com/mozilla/pontoon",
        primaryLanguage: {
          color: "#3572A5",
          name: "Python",
          id: "MDg6TGFuZ3VhZ2UxNDU=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnk2MjAyNzA2MQ==",
        name: "LocalizedMenu",
        nameWithOwner: "zam1024t/LocalizedMenu",
        description:
          "Localize Tool & Localized Menu for Sublime Text 2/3/4 End User. Localization with 简体中文(Simplified Chinese)/繁体中文(Traditional Chinese)/Русский(Russian)/Español(Spanish)/Հայերեն(Armenian)/Svenska(Swedish)/Français(French)/Português(Portuguese)/Deutsch(German)/Any other language.",
        updatedAt: "2022-05-27T17:56:43Z",
        createdAt: "2016-06-27T05:10:56Z",
        pushedAt: "2022-06-16T15:10:15Z",
        stargazerCount: 97,
        viewerHasStarred: false,
        url: "https://github.com/zam1024t/LocalizedMenu",
        primaryLanguage: {
          color: "#3572A5",
          name: "Python",
          id: "MDg6TGFuZ3VhZ2UxNDU=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnk3MTE0NDM1OQ==",
        name: "localize-router",
        nameWithOwner: "Greentube/localize-router",
        description: "An implementation of routes localisation for Angular",
        updatedAt: "2022-04-16T17:03:32Z",
        createdAt: "2016-10-17T13:59:27Z",
        pushedAt: "2022-06-02T22:37:01Z",
        stargazerCount: 190,
        viewerHasStarred: false,
        url: "https://github.com/Greentube/localize-router",
        primaryLanguage: {
          color: "#3178c6",
          name: "TypeScript",
          id: "MDg6TGFuZ3VhZ2UyODc=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnk1OTc3NjA4Ng==",
        name: "angular-cn",
        nameWithOwner: "angular/angular-cn",
        description: "Chinese localization of angular.io",
        updatedAt: "2022-06-22T21:02:49Z",
        createdAt: "2016-05-26T19:07:10Z",
        pushedAt: "2021-12-11T00:36:46Z",
        stargazerCount: 767,
        viewerHasStarred: false,
        url: "https://github.com/angular/angular-cn",
        primaryLanguage: {
          color: "#a86454",
          name: "Pug",
          id: "MDg6TGFuZ3VhZ2U1NjU=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnk3NzQyMjUyOQ==",
        name: "react-localize-redux",
        nameWithOwner: "ryandrewjohnson/react-localize-redux",
        description: "Dead simple localization for your React components",
        updatedAt: "2022-05-12T14:38:25Z",
        createdAt: "2016-12-27T03:21:37Z",
        pushedAt: "2022-06-23T20:15:16Z",
        stargazerCount: 383,
        viewerHasStarred: false,
        url: "https://github.com/ryandrewjohnson/react-localize-redux",
        primaryLanguage: {
          color: "#f1e05a",
          name: "JavaScript",
          id: "MDg6TGFuZ3VhZ2UxNDA=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
    ],
    __typename: "SearchResultItemConnection",
  },
};

export const searchDataPageTwo = {
  search: {
    repositoryCount: 17822,
    pageInfo: {
      startCursor: "Y3Vyc29yOjEz",
      hasNextPage: true,
      endCursor: "Y3Vyc29yOjI0",
      __typename: "PageInfo",
    },
    repositories: [
      {
        id: "MDEwOlJlcG9zaXRvcnkyMDkyMDYxNg==",
        name: "l10n-spain",
        nameWithOwner: "OCA/l10n-spain",
        description: "Odoo Spain Localization",
        updatedAt: "2022-06-23T14:10:26Z",
        createdAt: "2014-06-17T11:21:27Z",
        pushedAt: "2022-07-01T18:19:15Z",
        stargazerCount: 162,
        viewerHasStarred: false,
        url: "https://github.com/OCA/l10n-spain",
        primaryLanguage: {
          color: "#3572A5",
          name: "Python",
          id: "MDg6TGFuZ3VhZ2UxNDU=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkxNDA4MzIxOTQ=",
        name: "AndroidLocalizePlugin",
        nameWithOwner: "Airsaid/AndroidLocalizePlugin",
        description:
          ":earth_asia:  Android localization plugin. supports multiple languages and multiple translators.",
        updatedAt: "2022-06-23T13:21:25Z",
        createdAt: "2018-07-13T10:14:24Z",
        pushedAt: "2022-07-02T03:33:18Z",
        stargazerCount: 426,
        viewerHasStarred: false,
        url: "https://github.com/Airsaid/AndroidLocalizePlugin",
        primaryLanguage: {
          color: "#b07219",
          name: "Java",
          id: "MDg6TGFuZ3VhZ2UxNTg=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkxMDU2MDQ4MA==",
        name: "Localize",
        nameWithOwner: "delight-im/Localize",
        description: "[UNMAINTAINED] Collaborative Translation for Android",
        updatedAt: "2020-03-27T10:23:24Z",
        createdAt: "2013-06-07T23:11:11Z",
        pushedAt: "2016-06-07T17:26:26Z",
        stargazerCount: 47,
        viewerHasStarred: false,
        url: "https://github.com/delight-im/Localize",
        primaryLanguage: {
          color: "#4F5D95",
          name: "PHP",
          id: "MDg6TGFuZ3VhZ2UxNTE=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnk2NjMzOQ==",
        name: "localized_country_select",
        nameWithOwner: "karmi/localized_country_select",
        description:
          'Rails plugin for localized "country_select" helper with Rake task for downloading locales from Unicode.org\'s CLDR',
        updatedAt: "2022-06-18T14:16:31Z",
        createdAt: "2008-10-22T15:35:18Z",
        pushedAt: "2012-12-08T13:32:06Z",
        stargazerCount: 182,
        viewerHasStarred: false,
        url: "https://github.com/karmi/localized_country_select",
        primaryLanguage: {
          color: "#701516",
          name: "Ruby",
          id: "MDg6TGFuZ3VhZ2UxNDE=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkyMTA5NDk1MQ==",
        name: "localized-carbon",
        nameWithOwner: "LaravelRUS/localized-carbon",
        description: "A localizable version of Carbon",
        updatedAt: "2022-05-07T22:36:37Z",
        createdAt: "2014-06-22T13:55:23Z",
        pushedAt: "2019-12-14T10:00:12Z",
        stargazerCount: 139,
        viewerHasStarred: false,
        url: "https://github.com/LaravelRUS/localized-carbon",
        primaryLanguage: {
          color: "#4F5D95",
          name: "PHP",
          id: "MDg6TGFuZ3VhZ2UxNTE=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkxMjE1NjMwODM=",
        name: "vscode-loc",
        nameWithOwner: "microsoft/vscode-loc",
        description: "VS Code Localization Extension",
        updatedAt: "2022-06-27T17:43:36Z",
        createdAt: "2018-02-14T21:26:07Z",
        pushedAt: "2022-07-02T13:03:33Z",
        stargazerCount: 335,
        viewerHasStarred: false,
        url: "https://github.com/microsoft/vscode-loc",
        primaryLanguage: null,
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnk4OTI2NTg0",
        name: "localize-with-spreadsheet",
        nameWithOwner: "xvrh/localize-with-spreadsheet",
        description:
          "Create a localization file in Android or iOS format from a Google Spreadsheet",
        updatedAt: "2022-03-02T15:22:46Z",
        createdAt: "2013-03-21T10:39:56Z",
        pushedAt: "2021-08-20T09:25:25Z",
        stargazerCount: 124,
        viewerHasStarred: false,
        url: "https://github.com/xvrh/localize-with-spreadsheet",
        primaryLanguage: {
          color: "#f1e05a",
          name: "JavaScript",
          id: "MDg6TGFuZ3VhZ2UxNDA=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkyNzU1Mzg2OA==",
        name: "intl",
        nameWithOwner: "dart-lang/intl",
        description: "Internationalization and localization support",
        updatedAt: "2022-07-01T00:20:43Z",
        createdAt: "2014-12-04T18:26:32Z",
        pushedAt: "2022-06-07T02:12:31Z",
        stargazerCount: 453,
        viewerHasStarred: false,
        url: "https://github.com/dart-lang/intl",
        primaryLanguage: {
          color: "#00B4AB",
          name: "Dart",
          id: "MDg6TGFuZ3VhZ2UyNzc=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkxNzk3MDY5MDg=",
        name: "wagtail-localize",
        nameWithOwner: "wagtail/wagtail-localize",
        description: "Translation plugin for Wagtail CMS",
        updatedAt: "2022-06-13T07:10:25Z",
        createdAt: "2019-04-05T15:21:14Z",
        pushedAt: "2022-07-01T18:53:55Z",
        stargazerCount: 140,
        viewerHasStarred: false,
        url: "https://github.com/wagtail/wagtail-localize",
        primaryLanguage: {
          color: "#3572A5",
          name: "Python",
          id: "MDg6TGFuZ3VhZ2UxNDU=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkyODAwODQzMjQ=",
        name: "Hierarchical-Localization",
        nameWithOwner: "cvg/Hierarchical-Localization",
        description: "Visual localization made easy with hloc",
        updatedAt: "2022-07-01T03:03:31Z",
        createdAt: "2020-07-16T07:25:35Z",
        pushedAt: "2022-06-30T10:58:25Z",
        stargazerCount: 1600,
        viewerHasStarred: false,
        url: "https://github.com/cvg/Hierarchical-Localization",
        primaryLanguage: {
          color: "#3572A5",
          name: "Python",
          id: "MDg6TGFuZ3VhZ2UxNDU=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkzNzY5Njk2",
        name: "translate",
        nameWithOwner: "translate/translate",
        description:
          "Useful localization tools with Python API for building localization & translation systems",
        updatedAt: "2022-07-01T06:15:45Z",
        createdAt: "2012-03-19T23:05:29Z",
        pushedAt: "2022-07-02T05:28:52Z",
        stargazerCount: 698,
        viewerHasStarred: false,
        url: "https://github.com/translate/translate",
        primaryLanguage: {
          color: "#3572A5",
          name: "Python",
          id: "MDg6TGFuZ3VhZ2UxNDU=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
      {
        id: "MDEwOlJlcG9zaXRvcnkyMDY0ODc2Mw==",
        name: "l10n-italy",
        nameWithOwner: "OCA/l10n-italy",
        description: "Odoo Italian localization",
        updatedAt: "2022-06-30T18:02:05Z",
        createdAt: "2014-06-09T14:08:49Z",
        pushedAt: "2022-07-02T07:40:21Z",
        stargazerCount: 88,
        viewerHasStarred: false,
        url: "https://github.com/OCA/l10n-italy",
        primaryLanguage: {
          color: "#3572A5",
          name: "Python",
          id: "MDg6TGFuZ3VhZ2UxNDU=",
          __typename: "Language",
        },
        __typename: "Repository",
      },
    ],
    __typename: "SearchResultItemConnection",
  },
};

export default searchData;
