const data = {
  data: {
    viewer: {
      login: "ivanms1",
      name: "Iván",
      starredRepositories: {
        pageInfo: {
          startCursor: "Y3Vyc29yOnYyOpHOBXVEHA==",
          hasNextPage: false,
          endCursor: "Y3Vyc29yOnYyOpHOFIirZA==",
          __typename: "PageInfo",
        },
        repositories: [
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnkyODQ1NzgyMw==",
              name: "freeCodeCamp",
              nameWithOwner: "freeCodeCamp/freeCodeCamp",
              description:
                "freeCodeCamp.org's open-source codebase and curriculum. Learn to code for free.",
              updatedAt: "2022-07-02T20:06:14Z",
              createdAt: "2014-12-24T17:49:19Z",
              pushedAt: "2022-07-02T19:44:42Z",
              stargazerCount: 348357,
              viewerHasStarred: true,
              url: "https://github.com/freeCodeCamp/freeCodeCamp",
              primaryLanguage: {
                color: "#3178c6",
                name: "TypeScript",
                id: "MDg6TGFuZ3VhZ2UyODc=",
                __typename: "Language",
              },
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnkxMzQyMjg2MTA=",
              name: "Geckos-Team-43",
              nameWithOwner: "chingu-voyage5/Geckos-Team-43",
              description:
                "Add-project-description-here | Voyage-5 | chingu.io",
              updatedAt: "2018-08-12T05:00:26Z",
              createdAt: "2018-05-21T06:37:45Z",
              pushedAt: "2018-08-23T14:32:08Z",
              stargazerCount: 3,
              viewerHasStarred: true,
              url: "https://github.com/chingu-voyage5/Geckos-Team-43",
              primaryLanguage: {
                color: "#f1e05a",
                name: "JavaScript",
                id: "MDg6TGFuZ3VhZ2UxNDA=",
                __typename: "Language",
              },
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnkxMzYxNTc0MDc=",
              name: "Course",
              nameWithOwner: "hackerbayuniversity/Course",
              description:
                "Open Source course materials from HackerBay University",
              updatedAt: "2022-06-28T14:36:34Z",
              createdAt: "2018-06-05T09:58:39Z",
              pushedAt: "2018-10-29T16:55:48Z",
              stargazerCount: 68,
              viewerHasStarred: true,
              url: "https://github.com/hackerbayuniversity/Course",
              primaryLanguage: {
                color: "#f1e05a",
                name: "JavaScript",
                id: "MDg6TGFuZ3VhZ2UxNDA=",
                __typename: "Language",
              },
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnkxNTgwODgxMzY=",
              name: "Bears-Team-29",
              nameWithOwner: "chingu-voyage7/Bears-Team-29",
              description: "eCommerce site | Voyage-7 | https://chingu.io/",
              updatedAt: "2018-12-18T16:05:29Z",
              createdAt: "2018-11-18T13:44:51Z",
              pushedAt: "2018-12-20T09:52:01Z",
              stargazerCount: 1,
              viewerHasStarred: true,
              url: "https://github.com/chingu-voyage7/Bears-Team-29",
              primaryLanguage: {
                color: "#f1e05a",
                name: "JavaScript",
                id: "MDg6TGFuZ3VhZ2UxNDA=",
                __typename: "Language",
              },
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnk3OTI1MjgwOA==",
              name: "js-lingui",
              nameWithOwner: "lingui/js-lingui",
              description:
                "🌍📖 A readable, automated, and optimized (5 kb) internationalization for JavaScript",
              updatedAt: "2022-06-30T09:02:56Z",
              createdAt: "2017-01-17T17:26:46Z",
              pushedAt: "2022-06-23T21:19:03Z",
              stargazerCount: 3384,
              viewerHasStarred: true,
              url: "https://github.com/lingui/js-lingui",
              primaryLanguage: {
                color: "#3178c6",
                name: "TypeScript",
                id: "MDg6TGFuZ3VhZ2UyODc=",
                __typename: "Language",
              },
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==",
              name: "react",
              nameWithOwner: "facebook/react",
              description:
                "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
              updatedAt: "2022-07-02T20:15:38Z",
              createdAt: "2013-05-24T16:15:54Z",
              pushedAt: "2022-07-02T08:18:13Z",
              stargazerCount: 190753,
              viewerHasStarred: true,
              url: "https://github.com/facebook/react",
              primaryLanguage: {
                color: "#f1e05a",
                name: "JavaScript",
                id: "MDg6TGFuZ3VhZ2UxNDA=",
                __typename: "Language",
              },
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnkxOTAyNTQ2OTg=",
              name: "craft.js",
              nameWithOwner: "prevwong/craft.js",
              description:
                "🚀 A React Framework for building extensible drag and drop page editors",
              updatedAt: "2022-07-02T15:52:23Z",
              createdAt: "2019-06-04T18:08:50Z",
              pushedAt: "2022-06-21T13:41:58Z",
              stargazerCount: 5024,
              viewerHasStarred: true,
              url: "https://github.com/prevwong/craft.js",
              primaryLanguage: {
                color: "#3178c6",
                name: "TypeScript",
                id: "MDg6TGFuZ3VhZ2UyODc=",
                __typename: "Language",
              },
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnkyODgyMzI5MDA=",
              name: "nextjs-graphql-typescript",
              nameWithOwner: "ivanms1/nextjs-graphql-typescript",
              description: "GraphQL + TypeScript boilerplate for NextJS.",
              updatedAt: "2022-02-15T01:04:10Z",
              createdAt: "2020-08-17T16:38:59Z",
              pushedAt: "2022-07-01T06:03:10Z",
              stargazerCount: 7,
              viewerHasStarred: true,
              url: "https://github.com/ivanms1/nextjs-graphql-typescript",
              primaryLanguage: {
                color: "#3178c6",
                name: "TypeScript",
                id: "MDg6TGFuZ3VhZ2UyODc=",
                __typename: "Language",
              },
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnkzNzY3Mjc0ODA=",
              name: "next-js-template",
              nameWithOwner: "ivanms1/next-js-template",
              description: "Next.js template",
              updatedAt: "2022-02-15T04:11:34Z",
              createdAt: "2021-06-14T06:42:48Z",
              pushedAt: "2022-07-01T19:05:58Z",
              stargazerCount: 2,
              viewerHasStarred: true,
              url: "https://github.com/ivanms1/next-js-template",
              primaryLanguage: {
                color: "#3178c6",
                name: "TypeScript",
                id: "MDg6TGFuZ3VhZ2UyODc=",
                __typename: "Language",
              },
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnk0MDMwNjIyODk=",
              name: "project-shelf",
              nameWithOwner: "project-shelf/project-shelf",
              description: "A showcase app for your projects",
              updatedAt: "2022-05-16T12:24:18Z",
              createdAt: "2021-09-04T13:23:10Z",
              pushedAt: "2022-07-01T03:20:13Z",
              stargazerCount: 11,
              viewerHasStarred: true,
              url: "https://github.com/project-shelf/project-shelf",
              primaryLanguage: {
                color: "#3178c6",
                name: "TypeScript",
                id: "MDg6TGFuZ3VhZ2UyODc=",
                __typename: "Language",
              },
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnkxODYwOTAxNDE=",
              name: "meetncode",
              nameWithOwner: "meetncode/meetncode",
              description: "Meetups for developers",
              updatedAt: "2022-07-02T16:08:35Z",
              createdAt: "2019-05-11T05:05:10Z",
              pushedAt: "2022-06-02T21:09:47Z",
              stargazerCount: 2,
              viewerHasStarred: true,
              url: "https://github.com/meetncode/meetncode",
              primaryLanguage: {
                color: "#f1e05a",
                name: "JavaScript",
                id: "MDg6TGFuZ3VhZ2UxNDA=",
                __typename: "Language",
              },
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
          {
            node: {
              id: "MDEwOlJlcG9zaXRvcnkyNDYwNjg2NDk=",
              name: "weekly-projects",
              nameWithOwner: "florinpop17/weekly-projects",
              description:
                "Build a project every week to improve your coding skills",
              updatedAt: "2022-07-02T16:09:17Z",
              createdAt: "2020-03-09T15:12:42Z",
              pushedAt: "2020-12-26T00:12:26Z",
              stargazerCount: 420,
              viewerHasStarred: true,
              url: "https://github.com/florinpop17/weekly-projects",
              primaryLanguage: null,
              __typename: "Repository",
            },
            __typename: "StarredRepositoryEdge",
          },
        ],
        __typename: "StarredRepositoryConnection",
      },
      __typename: "User",
    },
  },
};

export default data;
